#!/usr/bin/env python3
"""Obsidian markdown report builder using Jinja2 templates."""

import json
import sys
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, BaseLoader

REPORT_TEMPLATE = """---
type: source
area: bitcoin-research
topics: [buybacks, {{ protocol_name | lower }}]
protocol: {{ protocol_name | lower }}
token: {{ token_symbol | upper }}
category: {{ category }}
status: review
created: {{ date }}
buyback_yield: {{ metrics.buyback_yield_pct | default('N/A') }}
pe_ratio: {{ metrics.pe_ratio | default('N/A') }}
---

# {{ protocol_name }} — Buyback Analysis

> **One-line summary**: {{ summary }}

## Key Metrics

| Metric | Value |
|--------|-------|
| Market Cap | {{ metrics.market_cap | format_usd }} |
| FDV | {{ metrics.fdv | format_usd }} |
| FDV/MCap | {{ metrics.fdv_mcap_ratio | default('N/A') }}x |
| Annual Revenue | {{ metrics.annual_revenue_est | format_usd }} |
| Buyback Allocation | {{ buyback_allocation }} |
| Annual Buyback | {{ metrics.annual_holders_revenue_est | format_usd }} |
| Buyback Yield | {{ metrics.buyback_yield_pct | default('N/A') }}% |
| P/E Ratio | {{ metrics.pe_ratio | default('N/A') }}x |
| Category | {{ category }} |

## Revenue Model

{{ revenue_model }}

## Buyback Mechanism

{{ buyback_mechanism }}

## Supply Dynamics

{{ supply_dynamics }}

---

## Analyst Perspectives

{% for analyst in analysts %}
### @{{ analyst.name }} — {{ analyst.lens }}

> Key question: "{{ analyst.question }}"

{{ analyst.analysis }}

**Verdict**: {{ analyst.verdict }}

{% endfor %}

---

## Consensus & Disagreement

### Points of Agreement
{{ agreement }}

### Points of Disagreement
{{ disagreement }}

### Analyst Verdict Summary

| Analyst | Verdict | Confidence |
|---------|---------|------------|
{% for analyst in analysts %}| @{{ analyst.name }} | {{ analyst.verdict }} | {{ analyst.confidence }} |
{% endfor %}

## Key Risks

{% for risk in risks %}{{ loop.index }}. {{ risk }}
{% endfor %}

## So What?

{{ so_what }}

---

*Generated by Ralph Buyback Research System — {{ date }}*
*Data sources: DefiLlama, CoinGecko, on-chain*
"""


def format_usd(value):
    """Format a number as USD string."""
    if value is None:
        return "N/A"
    try:
        value = float(value)
    except (TypeError, ValueError):
        return str(value)
    if abs(value) >= 1e9:
        return f"${value / 1e9:.2f}B"
    if abs(value) >= 1e6:
        return f"${value / 1e6:.1f}M"
    if abs(value) >= 1e3:
        return f"${value / 1e3:.1f}K"
    return f"${value:,.2f}"


def create_env() -> Environment:
    """Create Jinja2 environment with custom filters."""
    env = Environment(loader=BaseLoader())
    env.filters["format_usd"] = format_usd
    return env


def generate_report(
    protocol_name: str,
    token_symbol: str,
    category: str,
    summary: str,
    metrics: dict,
    buyback_allocation: str,
    revenue_model: str,
    buyback_mechanism: str,
    supply_dynamics: str,
    analysts: list,
    agreement: str,
    disagreement: str,
    risks: list,
    so_what: str,
) -> str:
    """Generate a complete Obsidian markdown report."""
    env = create_env()
    template = env.from_string(REPORT_TEMPLATE)

    return template.render(
        protocol_name=protocol_name,
        token_symbol=token_symbol,
        category=category,
        summary=summary,
        metrics=metrics,
        buyback_allocation=buyback_allocation,
        revenue_model=revenue_model,
        buyback_mechanism=buyback_mechanism,
        supply_dynamics=supply_dynamics,
        analysts=analysts,
        agreement=agreement,
        disagreement=disagreement,
        risks=risks,
        so_what=so_what,
        date=datetime.utcnow().strftime("%Y-%m-%d"),
    )


def generate_from_json(data_path: str) -> str:
    """Generate report from a pre-assembled JSON file."""
    with open(data_path) as f:
        data = json.load(f)
    return generate_report(**data)


def main():
    if len(sys.argv) < 2:
        print("Usage: python generator.py <report_data.json>")
        print("       python generator.py --example")
        sys.exit(1)

    if sys.argv[1] == "--example":
        # Print example data structure
        example = {
            "protocol_name": "ExampleProtocol",
            "token_symbol": "EXM",
            "category": "DEX",
            "summary": "Strong buyback program with sustainable revenue.",
            "metrics": {
                "market_cap": 1000000000,
                "fdv": 2000000000,
                "fdv_mcap_ratio": 2.0,
                "annual_revenue_est": 100000000,
                "annual_holders_revenue_est": 50000000,
                "buyback_yield_pct": 5.0,
                "pe_ratio": 10.0,
            },
            "buyback_allocation": "50% of fees",
            "revenue_model": "Trading fees from DEX activity.",
            "buyback_mechanism": "Continuous buyback via AMM.",
            "supply_dynamics": "60% circulating, 2-year unlock for remaining.",
            "analysts": [
                {
                    "name": "Charbonneau",
                    "lens": "Protocol Design Lens",
                    "question": "Is this well-designed?",
                    "analysis": "Analysis here...",
                    "verdict": "Bullish",
                    "confidence": "High",
                },
            ],
            "agreement": "- All agree revenue is sustainable",
            "disagreement": "- Disagree on cyclicality risk",
            "risks": ["Smart contract risk", "Competition", "Regulatory"],
            "so_what": "This protocol represents a strong buyback case study.",
        }
        print(json.dumps(example, indent=2))
        return

    report = generate_from_json(sys.argv[1])
    print(report)


if __name__ == "__main__":
    main()
